[package]
name = "embedded-devices"
edition = "2021"
version = "0.9.0"
authors = ["oddlama <oddlama@oddlama.org>"]
description = "Device driver implementations for many embedded sensors and devices"
documentation = "https://github.com/oddlama/embedded-devices"
homepage = "https://github.com/oddlama/embedded-devices"
repository = "https://github.com/oddlama/embedded-devices"
keywords = ["sensor", "embedded", "device", "driver", "peripheral"]
categories = ["embedded", "no-std", "hardware-support", "embedded-hal"]
license = "MIT OR Apache-2.0"

[dependencies]
embedded-hal = "1.0.0-rc.1"
embedded-hal-async = "1.0.0-rc.1"
embedded-registers = "0.9.0"

[features]
default = []
std = []
