[package]
name = "embedded-devices"
edition = "2021"
version = "0.0.1"
authors = ["oddlama <oddlama@oddlama.org>"]
description = "Device driver implementations for many embedded sensors and devices"
documentation = "https://docs.rs/embedded-devices"
homepage = "https://github.com/oddlama/embedded-devices"
repository = "https://github.com/oddlama/embedded-devices"
keywords = ["sensor", "embedded", "device", "driver", "peripheral"]
categories = ["embedded", "no-std", "hardware-support", "embedded-hal"]
license = "MIT OR Apache-2.0"

[dependencies]
bondrewd = { version = "0.1.14", default_features = false, features = ["derive"] }
defmt = "0.3.5"
embedded-hal = "1.0.0-rc.1"
embedded-hal-async = "1.0.0-rc.1"
#embedded-registers = "0.9.3"
embedded-registers = { path = "../embedded-registers/embedded-registers" }
uom = { version = "0.35.0", features = ["autoconvert", "f32", "f64", "si", "u8", "u16", "u32", "u64", "i8", "i16", "i32", "i64", "rational32", "rational64"], default-features = false }

[patch.crates-io]
embedded-registers-derive = { path = "../embedded-registers/embedded-registers-derive" }

[features]
default = []
std = []
